import { initializeApp } from "https://www.gstatic.com/firebasejs/11.0.2/firebase-app.js";
import { getAuth, GoogleAuthProvider, onAuthStateChanged, signInWithPopup, signOut } from "https://www.gstatic.com/firebasejs/11.0.2/firebase-auth.js";
import { getFirestore, collection, doc, addDoc, onSnapshot, orderBy, query, serverTimestamp, updateDoc } from "https://www.gstatic.com/firebasejs/11.0.2/firebase-firestore.js";
import { firebaseConfig } from "./firebase-config.js";

const app = initializeApp(firebaseConfig), auth = getAuth(app), db = getFirestore(app), provider = new GoogleAuthProvider();
const login = document.querySelector("#admin-login"), logout = document.querySelector("#admin-sign-out"), notice = document.querySelector("#admin-notice"), area = document.querySelector("#admin-chat-area"), status = document.querySelector("#admin-status"), conversations = document.querySelector("#conversation-list"), userLabel = document.querySelector("#selected-user"), list = document.querySelector("#admin-message-list"), form = document.querySelector("#admin-message-form"), input = document.querySelector("#admin-message-input");
let admin = null, selectedId = null, unsubscribeMessages = null;
const escapeText = (value) => { const div = document.createElement("div"); div.textContent = value; return div.innerHTML; };
const clock = (timestamp) => timestamp?.toDate ? timestamp.toDate().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }) : "Sending...";
function renderMessages(snapshot) { list.innerHTML = ""; snapshot.forEach((message) => { const data = message.data(); const el = document.createElement("div"); el.className = `message ${data.senderRole === "admin" ? "visitor" : "admin"}`; el.innerHTML = `${escapeText(data.text)}<small>${data.senderRole === "admin" ? "You" : "Visitor"} · ${clock(data.createdAt)}</small>`; list.appendChild(el); }); list.scrollTop = list.scrollHeight; }
function selectConversation(id, data) { selectedId = id; userLabel.textContent = `${data.visitorName || "Visitor"} — ${data.visitorEmail || ""}`; form.classList.remove("hidden"); document.querySelectorAll(".conversation").forEach((element) => element.classList.toggle("active", element.dataset.id === id)); if (unsubscribeMessages) unsubscribeMessages(); unsubscribeMessages = onSnapshot(query(collection(db, "conversations", id, "messages"), orderBy("createdAt")), renderMessages, (error) => alert(`Messages could not load: ${error.message}`)); }
function watchConversations() { onSnapshot(query(collection(db, "conversations"), orderBy("updatedAt", "desc")), (snapshot) => { conversations.innerHTML = ""; snapshot.forEach((item) => { const data = item.data(), button = document.createElement("button"); button.className = "conversation"; button.dataset.id = item.id; button.innerHTML = `<strong>${escapeText(data.visitorName || "Visitor")}</strong><small>${escapeText(data.visitorEmail || "")}</small>`; button.addEventListener("click", () => selectConversation(item.id, data)); conversations.appendChild(button); }); }, (error) => { status.textContent = "Access denied. Add your Firebase UID to the admins collection first."; alert(error.message); }); }
login.addEventListener("click", async () => { try { await signInWithPopup(auth, provider); } catch (error) { alert(`Google sign-in failed: ${error.message}`); } }); logout.addEventListener("click", () => signOut(auth));
onAuthStateChanged(auth, (user) => { admin = user; if (!user) { login.classList.remove("hidden"); logout.classList.add("hidden"); notice.classList.remove("hidden"); area.classList.add("hidden"); status.textContent = "Sign in with your admin Google account."; return; } login.classList.add("hidden"); logout.classList.remove("hidden"); notice.classList.add("hidden"); area.classList.remove("hidden"); status.textContent = `Signed in as ${user.email}`; watchConversations(); });
form.addEventListener("submit", async (event) => { event.preventDefault(); const text = input.value.trim(); if (!text || !selectedId || !admin) return; input.disabled = true; try { await addDoc(collection(db, "conversations", selectedId, "messages"), { text, senderId: admin.uid, senderRole: "admin", createdAt: serverTimestamp() }); await updateDoc(doc(db, "conversations", selectedId), { updatedAt: serverTimestamp(), lastMessage: text }); input.value = ""; } catch (error) { alert(`Reply failed: ${error.message}`); } finally { input.disabled = false; input.focus(); } });