import { initializeApp } from "https://www.gstatic.com/firebasejs/11.0.2/firebase-app.js";
import { getAuth, GoogleAuthProvider, onAuthStateChanged, signInWithPopup, signOut } from "https://www.gstatic.com/firebasejs/11.0.2/firebase-auth.js";
import { getFirestore, collection, doc, addDoc, onSnapshot, orderBy, query, serverTimestamp, setDoc, updateDoc } from "https://www.gstatic.com/firebasejs/11.0.2/firebase-firestore.js";
import { firebaseConfig } from "./firebase-config.js";

const app = initializeApp(firebaseConfig), auth = getAuth(app), db = getFirestore(app), provider = new GoogleAuthProvider();
const login = document.querySelector("#google-login"), logout = document.querySelector("#sign-out"), notice = document.querySelector("#login-notice"), area = document.querySelector("#chat-area"), status = document.querySelector("#chat-status"), list = document.querySelector("#message-list"), form = document.querySelector("#message-form"), input = document.querySelector("#message-input");
let unsubscribeMessages = null, currentUser = null;
const escapeText = (value) => { const div = document.createElement("div"); div.textContent = value; return div.innerHTML; };
const clock = (timestamp) => timestamp?.toDate ? timestamp.toDate().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }) : "Sending...";
function showMessages(snapshot) { list.innerHTML = ""; snapshot.forEach((message) => { const data = message.data(); const el = document.createElement("div"); el.className = `message ${data.senderRole === "admin" ? "admin" : "visitor"}`; el.innerHTML = `${escapeText(data.text)}<small>${data.senderRole === "admin" ? "Masum" : "You"} · ${clock(data.createdAt)}</small>`; list.appendChild(el); }); list.scrollTop = list.scrollHeight; }
async function openConversation(user) { const conversation = doc(db, "conversations", user.uid); await setDoc(conversation, { visitorName: user.displayName || "Visitor", visitorEmail: user.email || "", visitorPhoto: user.photoURL || "", updatedAt: serverTimestamp(), createdAt: serverTimestamp() }, { merge: true }); if (unsubscribeMessages) unsubscribeMessages(); unsubscribeMessages = onSnapshot(query(collection(conversation, "messages"), orderBy("createdAt")), showMessages, (error) => alert(`Chat could not load: ${error.message}`)); }
login.addEventListener("click", async () => { try { await signInWithPopup(auth, provider); } catch (error) { alert(`Google sign-in failed: ${error.message}`); } }); logout.addEventListener("click", () => signOut(auth));
onAuthStateChanged(auth, async (user) => { currentUser = user; if (!user) { if (unsubscribeMessages) unsubscribeMessages(); list.innerHTML = ""; login.classList.remove("hidden"); logout.classList.add("hidden"); notice.classList.remove("hidden"); area.classList.add("hidden"); status.textContent = "Sign in with Google to start a secure conversation."; return; } login.classList.add("hidden"); logout.classList.remove("hidden"); notice.classList.add("hidden"); area.classList.remove("hidden"); status.textContent = `Signed in as ${user.displayName || user.email}`; await openConversation(user); });
form.addEventListener("submit", async (event) => { event.preventDefault(); const text = input.value.trim(); if (!text || !currentUser) return; input.disabled = true; try { const conversation = doc(db, "conversations", currentUser.uid); await addDoc(collection(conversation, "messages"), { text, senderId: currentUser.uid, senderRole: "visitor", createdAt: serverTimestamp() }); await updateDoc(conversation, { updatedAt: serverTimestamp(), lastMessage: text }); input.value = ""; } catch (error) { alert(`Message failed: ${error.message}`); } finally { input.disabled = false; input.focus(); } });